LANG_MAP = {
    # Español y variantes
    "español": "spa",
    "en español": "spa",
    "castellano": "spa",
    "espanol": "spa",
    "spanish": "spa",
    # Latín
    "latin": "lat",
    "latín": "lat",
    # Náhuatl
    "nahuatl": "nah",
    "náhuatl": "nah",
    # ========================================
    # IDIOMAS EUROPEOS PRINCIPALES
    # ========================================
    # Alemán
    "alemán": "ger",
    "aleman": "ger",
    "german": "ger",
    "deutsch": "ger",
    # Francés
    "francés": "fre",
    "frances": "fre",
    "french": "fre",
    "français": "fre",
    # Inglés
    "inglés": "eng",
    "ingles": "eng",
    "english": "eng",
    # Italiano
    "italiano": "ita",
    "italian": "ita",
    # Portugués
    "portugués": "por",
    "portugues": "por",
    "portuguese": "por",
    # Ruso
    "ruso": "rus",
    "russian": "rus",
    # Polaco
    "polaco": "pol",
    "polish": "pol",
    "polski": "pol",
    # Neerlandés / Holandés
    "neerlandés": "dut",
    "neerlandes": "dut",
    "holandés": "dut",
    "holandes": "dut",
    "dutch": "dut",
    "nederlands": "dut",
    # Griego
    "griego": "gre",
    "greek": "gre",
    "ελληνικά": "gre",
    # Sueco
    "sueco": "swe",
    "swedish": "swe",
    "svenska": "swe",
    # Noruego
    "noruego": "nor",
    "norwegian": "nor",
    "norsk": "nor",
    # Danés
    "danés": "dan",
    "danes": "dan",
    "danish": "dan",
    "dansk": "dan",
    # Finlandés / Finés
    "finlandés": "fin",
    "finlandes": "fin",
    "finés": "fin",
    "fines": "fin",
    "finnish": "fin",
    "suomi": "fin",
    # Checo
    "checo": "cze",
    "czech": "cze",
    "čeština": "cze",
    # Húngaro
    "húngaro": "hun",
    "hungaro": "hun",
    "hungarian": "hun",
    "magyar": "hun",
    # Rumano
    "rumano": "rum",
    "romanian": "rum",
    "română": "rum",
    # Búlgaro
    "búlgaro": "bul",
    "bulgaro": "bul",
    "bulgarian": "bul",
    # Croata
    "croata": "hrv",
    "croatian": "hrv",
    "hrvatski": "hrv",
    # Serbio
    "serbio": "srp",
    "serbian": "srp",
    "srpski": "srp",
    # Eslovaco
    "eslovaco": "slo",
    "slovak": "slo",
    "slovenčina": "slo",
    # Esloveno
    "esloveno": "slv",
    "slovenian": "slv",
    "slovenščina": "slv",
    # Ucraniano
    "ucraniano": "ukr",
    "ukrainian": "ukr",
    # Catalán
    "catalán": "cat",
    "catalan": "cat",
    "català": "cat",
    # Vasco / Euskera
    "vasco": "baq",
    "euskera": "baq",
    "basque": "baq",
    "euskara": "baq",
    # Gallego
    "gallego": "glg",
    "galician": "glg",
    "galego": "glg",
    # Irlandés / Gaélico
    "irlandés": "gle",
    "irlandes": "gle",
    "irish": "gle",
    "gaeilge": "gle",
    # Escocés (Gaélico)
    "gaélico escocés": "gla",
    "gaelico escoces": "gla",
    "scottish gaelic": "gla",
    # Galés
    "galés": "wel",
    "gales": "wel",
    "welsh": "wel",
    "cymraeg": "wel",
    # Islandés
    "islandés": "ice",
    "islandes": "ice",
    "icelandic": "ice",
    "íslenska": "ice",
    # Lituano
    "lituano": "lit",
    "lithuanian": "lit",
    "lietuvių": "lit",
    # Letón
    "letón": "lav",
    "leton": "lav",
    "latvian": "lav",
    "latviešu": "lav",
    # Estonio
    "estonio": "est",
    "estonian": "est",
    "eesti": "est",
    # Maltés
    "maltés": "mlt",
    "maltes": "mlt",
    "maltese": "mlt",
    "malti": "mlt",
    # Albanés
    "albanés": "alb",
    "albanes": "alb",
    "albanian": "alb",
    "shqip": "alb",
    # Macedonio
    "macedonio": "mac",
    "macedonian": "mac",
    # Bosnio
    "bosnio": "bos",
    "bosnian": "bos",
    # Luxemburgués
    "luxemburgués": "ltz",
    "luxemburgues": "ltz",
    "luxembourgish": "ltz",
    # Bretón
    "bretón": "bre",
    "breton": "bre",
    # Occitano
    "occitano": "oci",
    "occitan": "oci",
    # Sardo
    "sardo": "srd",
    "sardinian": "srd",
    # Friulano
    "friulano": "fur",
    "friulian": "fur",
    # Corso
    "corso": "cos",
    "corsican": "cos",
    # Romaní
    "romaní": "rom",
    "romani": "rom",
    "romany": "rom",
    # Yidis
    "yidis": "yid",
    "yiddish": "yid",
    # ========================================
    # VARIANTES Y CASOS ESPECIALES
    # ========================================
    # Multilingüe
    "multilingüe": "mul",
    "multilingual": "mul",
    "varios idiomas": "mul",
    "multiple languages": "mul",
    # Sin contenido lingüístico
    "sin idioma": "zxx",
    "no linguistic content": "zxx",
    # Idioma indeterminado
    "indeterminado": "und",
    "undetermined": "und",
    "desconocido": "und",
    "unknown": "und",
}
